### ISSUE TITLE
Missing Code For Producing Links?

### ISSUE THREAD

**Issue by sunscreem** [spatie/laravel-link-checker#14]
In the [crawlReport](https://github.com/spatie/laravel-link-checker/blob/386c016d999f917fc6f62da6faf8a056159c6f35/resources/views/crawlReport.blade.php#L11) email view there is a global function `link_to`:

``` 
@foreach($urls as $url)
        <li>{!! link_to($url) !!} </li>
@endforeach
```

This helper can't be found. I've had a search through all the other spatie opensource projects and can't find it.

**Comment by freekmurze** [comment]
That function is [defined in laravel-collection-html](https://github.com/LaravelCollective/html/blob/478288d8bc5535ea03932ac2f1766182f7cd58cc/src/helpers.php#L15). That package was not required in the `composer.json` of this package, which is obviously not good.

In our projects this was working accidentally because we require that html package there.

I've tagged a new release that does not use `link_to` anymore.

Thanks for reporting this.
